name: Add Mixpanel Annotations on Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  annotate_mixpanel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      run: |
        echo "${{ github.token }}" > ~/.gh_token
        gh auth login --with-token < ~/.gh_token

    - name: Get merged PRs for the release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Fetching merged PRs..."
        PRS=$(gh pr list --state merged --search "is:merged" --json title,url,mergedAt,author)
        echo "PR Data: $PRS"
        echo "MERGED_PRS=$PRS" >> $GITHUB_ENV

    - name: Print annotation text for each PR
      run: |
        echo "Processing PRs to print annotations"

        # Check if the PRS variable is empty
        if [ -z "${MERGED_PRS}" ]; then
          echo "No merged PRs found for the release."
          exit 0
        fi

        # Set the version number dynamically from the release tag
        version="${{ github.event.release.tag_name }}"

        echo "${MERGED_PRS}" | jq -c '.[]' | while read -r pr; do
          title=$(echo "$pr" | jq -r '.title')
          url=$(echo "$pr" | jq -r '.url')
          githubuser=$(echo "$pr" | jq -r '.author.login')
          release_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Construct annotation text in the required format (version: PR Title by @githubuser)
          annotation_text="(version: ${version}: ${title} by @${githubuser})"

          # Print the annotation text for testing
          echo "Annotation text: ${annotation_text}"
        done

    - name: Confirm test completion
      run: echo "Test run for printing annotation texts completed."
