name: Get Merged PRs for Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true

jobs:
  fetch_prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

      
    - name: Set up GitHub CLI
      run: |
        echo "${{ github.token }}" > ~/.gh_token
        gh auth login --with-token < ~/.gh_token

    - name: Get Merged PRs
      run: |
        RELEASE_TAG="${{ github.event.inputs.release_tag }}"
        echo "Fetching PRs merged into release $RELEASE_TAG..."

        # Get the commit SHA of the release tag
        RELEASE_COMMIT=$(gh release view "$RELEASE_TAG" --json targetCommitish -q .targetCommitish)

        # Get PRs merged in the release commit range
        gh pr list --state merged --json title,number,mergedAt,mergeCommit \
          --search "merged:$RELEASE_COMMIT" \
          | jq -r '.[] | {title, number, mergedAt}'
