name: List All Merged Pull Requests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  list_merged_prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository with tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all commit history and tags

      - name: List all merged PRs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release list --json tagName,publishedAt --jq '.[] | "\(.tagName)"' > releases.txt

      - name: List merged PRs with their release tags
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Merged PRs with their associated releases:"
          # Extract the commit SHA from the mergeCommit object
          gh pr list --state merged --json number,title,mergeCommit,mergedAt --jq '.[] | [.number, .title, .mergeCommit.oid, .mergedAt] | @csv' > merged_prs.csv
          
          # Loop through PRs and match them with releases
          while IFS=, read -r pr_number pr_title pr_commit_sha pr_merged_at; do
            for release in $(cat releases.txt); do
              if git merge-base --is-ancestor "$pr_commit_sha" "$release"; then
                echo "PR #$pr_number: $pr_title merged at $pr_merged_at, included in release $release"
                break
              fi
            done
          done < merged_prs.csv
