name: Print PR Info on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  print-pr-info:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print PR Info
        run: |
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Pull Request Author: ${{ github.event.pull_request.user.login }}"
          echo "Pull Request Merged By: ${{ github.event.pull_request.merged_by.login }}"
          echo "Pull Request URL: ${{ github.event.pull_request.html_url }}"
