name: Create Mixpanel Annotation on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  create-annotation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Mixpanel Annotation
        env:
          MIXPANEL_AUTH_TOKEN: ${{ secrets.MIXPANEL_AUTH_TOKEN }}
        run: |
          curl --request POST \
            --url 'https://mixpanel.com/api/app/workspaces/3331267/annotations' \
            --header "Authorization: Basic $MIXPANEL_AUTH_TOKEN" \
            --header "Content-Type: application/json" \
            --data-raw '{"date":"2024-10-06 14:15:00","description":"v1.0.5 - JSON support"}'
