name: Create Mixpanel Annotation on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  create-annotation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tzdata and set Jordan Time
        run: |
          sudo apt-get install -y tzdata
          sudo ln -fs /usr/share/zoneinfo/Asia/Amman /etc/localtime
          sudo dpkg-reconfigure -f noninteractive tzdata
          

      - name: Create Mixpanel Annotation
        run: |
          curl --request POST \
            --url 'https://mixpanel.com/api/app/workspaces/3331267/annotations' \
            --header 'authorization: Basic ${{ secrets.MIXPANEL_AUTH_TOKEN }}' \
            --header "Content-Type: application/json" \
            --data-raw '{
              "date": "'"$(date +"%Y-%m-%d %H:%M:%S")"'",
              "description": "PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }} (Author: ${{ github.event.pull_request.user.login }}) Link: ${{ github.event.pull_request.html_url }}"
            }'
