name: Create Mixpanel Annotation on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  create-annotation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Mixpanel Annotation
        env:
          MIXPANEL_AUTH_TOKEN: ${{ secrets.MIXPANEL_AUTH_TOKEN }}
        run: |
          echo "Creating Mixpanel annotation for PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }} (Author: ${{ github.event.pull_request.user.login }})"
          echo "Using Mixpanel Auth Token: $MIXPANEL_AUTH_TOKEN"
          # Set the date in the desired format
          formatted_date=$(date --utc +"%Y-%m-%d %H:%M:%S")
          echo "Current time: $formatted_date"
          curl --request POST \
            --url 'https://mixpanel.com/api/app/workspaces/3331267/annotations' \
            --header 'authorization: Basic ${{ secrets.MIXPANEL_AUTH_TOKEN }}' \
            --header "Content-Type: application/json" \
            --data-raw '{
              "date": "'"$formatted_date"'",
              "description": "PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }} (Author: ${{ github.event.pull_request.user.login }}) Link: ${{ github.event.pull_request.html_url }}"
            }'
