name: Create Mixpanel Annotation on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  create-annotation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Mixpanel Annotation
        env:
          MIXPANEL_AUTH_TOKEN: ${{ secrets.MIXPANEL_AUTH_TOKEN }}
        run: |
          current_date=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
          curl --request POST \
            --url 'https://mixpanel.com/api/app/workspaces/3331267/annotations' \
            --header "Authorization: Basic $(echo -n 'github.d6b7a3.mp-service-account:$MIXPANEL_AUTH_TOKEN' | base64)" \
            --header "Content-Type: application/json" \
            --data-raw '{
              "date": "'$current_date'",
              "description": "PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }} (Author: ${{ github.event.pull_request.user.login }}) Link: ${{ github.event.pull_request.html_url }}"
            }'
