name: Create Mixpanel Annotation on Release

on:
  release:
    types:
      - published

jobs:
  create-annotation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Mixpanel Annotation
        run: |
          curl --request POST \
            --url 'https://mixpanel.com/api/app/workspaces/3331267/annotations' \
            --header 'authorization: Basic ${{ secrets.MIXPANEL_AUTH_TOKEN }}' \
            --header "Content-Type: application/json" \
            --data-raw '{
              "date": "'"$(date --utc +"%Y-%m-%d %H:%M:%S")"'",
              "description": "Release: ${{ github.event.release.tag_name }} - ${{ github.event.release.name }} Link: ${{ github.event.release.html_url }}"
            }'
