name: Print Message on Push

on:
  push:
    branches:
      - '*'  # This means it will trigger on all branches

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "Hello, this is a push event!"
